checks:
  php:
    code_rating: true
    duplication: false

filter:
  excluded_paths:
    - tests/*
    - examples/*
    - vendor/*
    - socket/*
    - hyper-run

build:

  environment:
    php: '7.0.8'

  dependencies:
    before:
      - 'composer install'
      - './vendor/bin/codecept build'
      - './hyper-run -S localhost:8080 -s localhost:8081 -n 5 -t examples &'

  tests:
    override:
      -
        command: './vendor/bin/codecept run unit'
